steps:
  - name: gradle:8.12-jdk21-alpine
    id: test
    entrypoint: gradle
    args: [ '-p', 'fetch-data-cloud-func', 'test' ]
  - name: gradle:8.12-jdk21-alpine
    id: build
    entrypoint: gradle
    args: [ '-p', 'fetch-data-cloud-func', 'clean', 'shadowJar' ]
    waitFor:
      - test
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:426.0.0-alpine
    args:
      - gcloud
      - functions
      - deploy
      - fetch-static-gtfs-data
      - --ingress-settings=internal-only
      - --gen2
      - --entry-point=com.github.ajablonski.FetchStaticGtfsData
      - --region=us-central1
      - --source=fetch-data-cloud-func/app/build/libs
      - --trigger-topic=fetch-static-gtfs-data-triggers
      - --run-service-account=gtfs-fetch@transit-stats-chicago.iam.gserviceaccount.com
      - --runtime=java21
      - --max-instances=1
      - --memory=384MiB
    waitFor:
      - build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:426.0.0-alpine
    args:
      - gcloud
      - functions
      - deploy
      - fetch-realtime-gtfs-data
      - --gen2
      - --ingress-settings=internal-only
      - --entry-point=com.github.ajablonski.FetchRealtimeGtfsData
      - --region=us-central1
      - --source=fetch-data-cloud-func/app/build/libs
      - --trigger-topic=fetch-realtime-gtfs-data-triggers
      - --runtime=java21
      - --max-instances=1
      - --memory=384MiB
      - --set-secrets=/etc/secrets/gtfs_secrets.json=gtfs-secrets-cta:1
    waitFor:
      - build
