steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - functions
      - deploy
      - fetch-gtfs-data
      - --region=us-central1
      - --source=fetch-data-cloud-func
      - --trigger-topic=fetch-gtfs-data-triggers
      - --runtime=java17
