steps:
  - name: gradle:7.4-jdk17
    entrypoint: gradle
    args: ['-p', 'fetch-data-cloud-func', 'shadowJar']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - fetch-gtfs-data
      - --ingress-settings=internal-only
      - --entry-point=com.github.ajablonski.FetchStaticGtfsData
      - --region=us-central1
      - --source=fetch-data-cloud-func/app/build/libs
      - --trigger-topic=fetch-gtfs-data-triggers
      - --runtime=java17
      - --max-instances=1
