/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.ajablonski

import com.google.cloud.functions.BackgroundFunction
import com.google.cloud.functions.Context
import java.time.Instant
import java.util.logging.Logger

class FetchStaticGtfsData : BackgroundFunction<PubSubMessage> {
    override fun accept(payload: PubSubMessage?, context: Context?) {
        logger.info("Attempting to fetch data at ${Instant.now()}")
    }

    companion object {
        private val logger = Logger.getLogger(FetchStaticGtfsData::class.java.name)
    }
}

data class PubSubMessage(
    val data: String,
    val messageID: String,
    val publishTime: String,
    val attributes: Map<String, String>
)
