/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.ajablonski

import com.google.cloud.functions.BackgroundFunction
import com.google.cloud.functions.Context
import com.google.events.cloud.pubsub.v1.Message
import java.time.Instant
import java.util.logging.Logger

class FetchStaticGtfsData : BackgroundFunction<Message> {
    override fun accept(payload: Message?, context: Context?) {
        logger.info("Attempting to fetch data at ${Instant.now()}")
    }

    companion object {
        private val logger = Logger.getLogger(FetchStaticGtfsData::class.java.name)
    }
}
